-- DÉSACTIVER RLS - EXÉCUTEZ CECI DANS SUPABASE SQL EDITOR

ALTER TABLE anonymous_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE posts DISABLE ROW LEVEL SECURITY;
ALTER TABLE comments DISABLE ROW LEVEL SECURITY;
ALTER TABLE post_reactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE comment_likes DISABLE ROW LEVEL SECURITY;
ALTER TABLE drafts DISABLE ROW LEVEL SECURITY;
ALTER TABLE post_views DISABLE ROW LEVEL SECURITY;
ALTER TABLE post_moods DISABLE ROW LEVEL SECURITY;
ALTER TABLE post_tags DISABLE ROW LEVEL SECURITY;
ALTER TABLE tags DISABLE ROW LEVEL SECURITY;
ALTER TABLE draft_moods DISABLE ROW LEVEL SECURITY;
ALTER TABLE draft_tags DISABLE ROW LEVEL SECURITY;
ALTER TABLE reaction_counts DISABLE ROW LEVEL SECURITY;
ALTER TABLE moods DISABLE ROW LEVEL SECURITY;
ALTER TABLE reaction_types DISABLE ROW LEVEL SECURITY;
